#!/usr/bin/env python3
"""Build src/web/index_html_gz.h from webui/.

Inlines style.css and app.js into index.html, gzips the result (level 9,
mtime 0 so the output is deterministic) and writes a C header with
INDEX_HTML_GZ[], INDEX_HTML_GZ_LEN, INDEX_HTML_ETAG and INDEX_HTML_CSP (a
Content-Security-Policy that allows exactly the inlined script and style by
hash).

  python tools/build_web.py           # regenerate the header
  python tools/build_web.py --check   # exit 1 if the committed header is stale

--check compares the *decompressed* page, the ETag and the CSP rather than
raw gzip bytes, so a different zlib on the developer machine cannot cause a
false failure in CI.
"""
import argparse
import base64
import gzip
import hashlib
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEBUI = ROOT / "webui"
OUT = ROOT / "src" / "web" / "index_html_gz.h"
BUDGET = 20 * 1024


def strip_lines(text: str) -> str:
    """Remove leading indentation and blank lines (safe for HTML, CSS and the JS in webui/)."""
    return "\n".join(line.strip() for line in text.splitlines() if line.strip())


def build_page() -> str:
    html = (WEBUI / "index.html").read_text(encoding="utf-8")
    css = (WEBUI / "style.css").read_text(encoding="utf-8")
    js = (WEBUI / "app.js").read_text(encoding="utf-8")
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    html = re.sub(r"<!--.*?-->", "", html, flags=re.S)
    # Function replacements: CSS/JS may contain backslashes that re would read as group references.
    css_inline = "<style>" + strip_lines(css) + "</style>"
    js_inline = "<script>" + strip_lines(js) + "</script>"
    html, n_css = re.subn(r'<link[^>]*href="style\.css"[^>]*>', lambda _m: css_inline, html)
    html, n_js = re.subn(r'<script[^>]*src="app\.js"[^>]*></script>', lambda _m: js_inline, html)
    if n_css != 1 or n_js != 1:
        sys.exit("index.html must reference style.css and app.js exactly once")
    return strip_lines(html) + "\n"


def etag_for(page: bytes) -> str:
    return '"' + hashlib.sha256(page).hexdigest()[:16] + '"'


def csp_for(page: str) -> str:
    def source_hash(tag: str) -> str:
        blocks = re.findall(rf"<{tag}>(.*?)</{tag}>", page, flags=re.S)
        if len(blocks) != 1:
            sys.exit(f"expected exactly one inline <{tag}> in the page")
        return "'sha256-" + base64.b64encode(hashlib.sha256(blocks[0].encode("utf-8")).digest()).decode() + "'"

    return (
        f"default-src 'none'; script-src {source_hash('script')}; style-src {source_hash('style')}; "
        "connect-src 'self' ws: wss:; img-src 'self' data:; form-action 'self'; frame-ancestors 'none'; base-uri 'none'"
    )


def render_header(page: bytes, gz: bytes, csp: str) -> str:
    body = "\n".join("  " + ", ".join("0x%02x" % b for b in gz[i : i + 16]) + "," for i in range(0, len(gz), 16))
    return (
        "// GENERATED by tools/build_web.py from webui/ -- do not edit by hand.\n"
        "#pragma once\n\n"
        "#include <pgmspace.h>\n#include <stddef.h>\n#include <stdint.h>\n\n"
        "// Gzipped single page console (index.html with style.css and app.js inlined).\n"
        f"static const size_t INDEX_HTML_GZ_LEN = {len(gz)};\n"
        f"static const char INDEX_HTML_ETAG[] = {etag_for(page)};\n"
        f'static const char INDEX_HTML_CSP[] = "{csp}";\n'
        f"static const uint8_t INDEX_HTML_GZ[] PROGMEM = {{\n{body}\n}};\n"
    )


def committed() -> tuple[bytes, str, str] | None:
    if not OUT.exists():
        return None
    text = OUT.read_text(encoding="utf-8")
    etag = re.search(r'INDEX_HTML_ETAG\[\] = ("[0-9a-f]+");', text)
    csp = re.search(r'INDEX_HTML_CSP\[\] = "([^"]*)";', text)
    data = re.search(r"INDEX_HTML_GZ\[\] PROGMEM = \{(.*?)\};", text, flags=re.S)
    if not etag or not csp or not data:
        return None
    raw = bytes(int(tok, 16) for tok in re.findall(r"0x[0-9a-fA-F]{2}", data.group(1)))
    try:
        return gzip.GzipFile(fileobj=io.BytesIO(raw)).read(), etag.group(1), csp.group(1)
    except OSError:
        return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify the committed header matches webui/")
    args = parser.parse_args()

    page_text = build_page()
    page = page_text.encode("utf-8")
    csp = csp_for(page_text)
    gz = gzip.compress(page, compresslevel=9, mtime=0)
    print(f"page: {len(page)} bytes raw, {len(gz)} bytes gzipped (budget {BUDGET})")
    if len(gz) > BUDGET:
        print("error: gzipped page exceeds the budget", file=sys.stderr)
        return 1

    if args.check:
        if committed() != (page, etag_for(page), csp):
            print(f"error: {OUT.relative_to(ROOT)} is stale, run: python tools/build_web.py", file=sys.stderr)
            return 1
        print("ok: generated header is up to date")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render_header(page, gz, csp), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
